### ISSUE TITLE
[Feature request] Search contacts

### ISSUE THREAD

**Issue by slarrain** [normen/whatscli#66] opened 2022-03-04 17:06 UTC
First, I want to thank you for this awesome app. I'm using it daily and is so cool to be able to use WhatsApp on the CLI.

Second, I wanted to ask for a feature, if it is possible and not too hard.

I have lots and lots of contacts, so when using whatsapp web or the android app, I regularly search for a contact when I  want to chat with them. In WhatsCli, you have to manually scroll down one by one until you find the one you want. It would be great if you could search for a contact, like for example typing `/name` and the cursor would go to that contact or maybe would display a subset that matches the search. 

I have no idea how hard this feature would be to implement, since I don't know any `go`. Had it been on python, I'd love to contribute. Again, many thanks!

**Comment by normen** [comment] 2022-03-04 17:30
Duplicate of #14

**Closed by normen** 2022-03-04 17:30 UTC

**Comment by slarrain** [comment] 2022-03-04 21:24
My bad. Should've checked better.
