### ISSUE TITLE
After scanning the QR code, the process ends with code 2

### ISSUE THREAD

**Issue by masioware** [normen/whatscli#71] opened 2022-04-08 17:22 UTC
This error happens every time the QR code is scanned

![image](https://user-images.githubusercontent.com/53904925/162491089-623a17f3-3dfe-4c4d-9d0b-0f1e0c1a2a27.png)

**Comment by masioware** [comment] 2022-04-08 17:32
I'm running in the windows terminal, but even in another environment the same error persists

**Comment by MiragonMx** [comment] 2022-04-08 21:21
It's the same for me (minus the shown exit code, but the error starts identically) and it somehow also messes with my terminal afterwards which starts spitting gibberish even from mouse movements...
Been like this since the WhatsApp update, that allows for multiple devices to stay online independently, I suppose there is a connection there to some API changes or something similar :/

I have no idea how that could be fixed sadly but would love to be able to go on use the TUI!

**Comment by normen** [comment] 2022-04-09 12:03
Duplicate of #64

**Closed by normen** 2022-04-09 12:03 UTC
